command: ["python", "app.py"]
env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: "YOUR_DATABRICKS_SERVER_HOSTNAME"
  - name: DATABRICKS_HTTP_PATH
    value: "YOUR_DATABRICKS_HTTP_PATH"
  - name: DATABRICKS_TOKEN
    value: "YOUR_DATABRICKS_TOKEN"
# NOTE: Use app.yaml.local with real credentials for deployment (excluded from git)
